### ISSUE TITLE
Whenever using the reddit companion to submit articles, the last letter of the given title can be chopped off.

### ISSUE THREAD

**Issue by knpwrs** [reddit-archive/reddit-companion#25]
This only happens when clicking the submit button, not when pressing enter on the keyboard. The length of the title doesn't matter. This issue is consistent with all pages I have tried. Check out the following gallery: http://imgur.com/a/8m2qq

This to me seems like somebody copy-pasted some non-working code at an early stage instead of using a common function and proper code reuse. I haven't actually peeked at the extension code myself, however.

**Comment by mhweaver** [comment]
It uses the `keypress` event to know when to update the Submit button's link. 
It looks like the `keypress` event fires before the text actually changes, so it sets the link to what the text was right _before_ you hit the key (hitting enter fires the same event, so it sets it correctly, since the text you want was already there when it fired).

The `keyup` event doesn't have the same problem, so the easy fix is to just change the event to that (pull request submitted that does just that).
